export const ABSENSI_CREATE_REQUEST = "ABSENSI_CREATE_REQUEST";
export const ABSENSI_CREATE_SUCCESS = "ABSENSI_CREATE_SUCCESS";
export const ABSENSI_CREATE_FAIL = "ABSENSI_CREATE_FAIL";
export const ABSENSI_CREATE_RESET = "ABSENSI_CREATE_RESET";

export const ABSENSI_DETAIL_REQUEST = "ABSENSI_DETAIL_REQUEST";
export const ABSENSI_DETAIL_SUCCESS = "ABSENSI_DETAIL_SUCCESS";
export const ABSENSI_DETAIL_FAIL = "ABSENSI_DETAIL_FAIL";
export const ABSENSI_DETAIL_RESET = "ABSENSI_DETAIL_RESET";

export const ABSENSI_COUNT_REQUEST = "ABSENSI_COUNT_REQUEST";
export const ABSENSI_COUNT_SUCCESS = "ABSENSI_COUNT_SUCCESS";
export const ABSENSI_COUNT_FAIL = "ABSENSI_COUNT_FAIL";
export const ABSENSI_COUNT_RESET = "ABSENSI_COUNT_RESET";


export const ABSENSI_LIST_REQUEST = "ABSENSI_LIST_REQUEST";
export const ABSENSI_LIST_SUCCESS = "ABSENSI_LIST_SUCCESS";
export const ABSENSI_LIST_FAIL = "ABSENSI_LIST_FAIL";
export const ABSENSI_LIST_RESET = "ABSENSI_LIST_RESET";
