export const DIVISI_LIST_REQUEST = "DIVISI_LIST_REQUEST";
export const DIVISI_LIST_SUCCESS = "DIVISI_LIST_SUCCESS";
export const DIVISI_LIST_FAIL = "DIVISI_LIST_FAIL";
export const DIVISI_LIST_RESET = "DIVISI_LIST_RESET";

export const DIVISI_DETAIL_REQUEST = "DIVISI_DETAIL_REQUEST";
export const DIVISI_DETAIL_SUCCESS = "DIVISI_DETAIL_SUCCESS";
export const DIVISI_DETAIL_FAIL = "DIVISI_DETAIL_FAIL";
export const DIVISI_DETAIL_RESET = "DIVISI_DETAIL_RESET";

export const DIVISI_CREATE_REQUEST = "DIVISI_CREATE_REQUEST";
export const DIVISI_CREATE_SUCCESS = "DIVISI_CREATE_SUCCESS";
export const DIVISI_CREATE_FAIL = "DIVISI_CREATE_FAIL";

export const DIVISI_DELETE_REQUEST = "DIVISI_DELETE_REQUEST";
export const DIVISI_DELETE_SUCCESS = "DIVISI_DELETE_SUCCESS";
export const DIVISI_DELETE_FAIL = "DIVISI_DELETE_FAIL";

export const DIVISI_UPDATE_REQUEST = "DIVISI_UPDATE_REQUEST";
export const DIVISI_UPDATE_SUCCESS = "DIVISI_UPDATE_SUCCESS";
export const DIVISI_UPDATE_FAIL = "DIVISI_UPDATE_FAIL";
