export const TIME_DETAIL_REQUEST = "TIME_DETAIL_REQUEST";
export const TIME_DETAIL_SUCCESS = "TIME_DETAIL_SUCCESS";
export const TIME_DETAIL_FAIL = "TIME_DETAIL_FAIL";
export const TIME_DETAIL_RESET = "TIME_DETAIL_RESET";

export const TIME_UPDATE_REQUEST = "TIME_UPDATE_REQUEST";
export const TIME_UPDATE_SUCCESS = "TIME_UPDATE_SUCCESS";
export const TIME_UPDATE_FAIL = "TIME_UPDATE_FAIL";