# Generated by Django 3.2.16 on 2022-11-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_absensikaryawan_jamkerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamKerjaAktif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_kerja', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jamkerja')),
            ],
        ),
    ]
