# Generated by Django 3.2.16 on 2022-11-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jamkerjaaktif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absensikaryawan',
            old_name='waktu',
            new_name='jam',
        ),
    ]
