# Generated by Django 3.2.16 on 2022-11-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_waktu_absensikaryawan_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilkaryawan',
            name='divisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.divisikerja'),
        ),
        migrations.AlterField(
            model_name='profilkaryawan',
            name='jenis_kelamin',
            field=models.TextField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], null=True),
        ),
        migrations.AlterField(
            model_name='profilkaryawan',
            name='nik',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profilkaryawan',
            name='tgl_lahir',
            field=models.DateField(null=True),
        ),
    ]
