# Generated by Django 3.2.16 on 2022-11-15 03:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221114_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilkaryawan',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to=core.models.user_foto_file_path),
        ),
    ]
