# Generated by Django 3.2.16 on 2022-11-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221115_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JamKerjaAktif',
        ),
    ]
