# Generated by Django 3.2.16 on 2022-11-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_jamkerjaaktif'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilKaryawan',
            new_name='DetilAkun',
        ),
        migrations.AlterField(
            model_name='absensikaryawan',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
