# Generated by Django 3.2.16 on 2022-11-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221115_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisiKerja',
            new_name='Divisi',
        ),
    ]
