# Generated by Django 3.2.16 on 2022-11-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_divisikerja_divisi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetilAkun',
            new_name='Profil',
        ),
    ]
