# Generated by Django 3.2.16 on 2022-11-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='divisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.divisi'),
        ),
    ]
