# Generated by Django 3.2.16 on 2022-11-18 00:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AddField(
            model_name='profil',
            name='foto',
            field=models.ImageField(null=True, upload_to=core.models.user_foto_file_path),
        ),
    ]
