# Generated by Django 3.2.16 on 2022-11-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221118_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='jam',
            field=models.DateTimeField(),
        ),
    ]
