# Generated by Django 3.2.16 on 2022-12-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_absensi_jam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='keterangan',
            field=models.CharField(choices=[('M', 'Masuk'), ('P', 'Pulang')], max_length=255, null=True),
        ),
    ]
