# Generated by Django 3.2.16 on 2022-12-02 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_absensi_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='jam',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
